Graph 추가, text 매치
mijien0179/PCTORY pull request #12
Opened 2022-05-19 08:46 UTC by cacaocoffee

text가 선택한 일,주,월간에 맞게 변경되며 그래프 갯수 추가. 기존 form1에 있던
toolstripmenu name들  알맞게 수정

2022-05-19 11:00 UTC, mijien0179 requested changes
몇 가지 수정하면 좋을 부분이 보이는데, 해당 부분에 대한 설명을 해주세요.
코드 상의 문제는 없으니 서로 합의가 완료되면 `Approve`하겠습니다.

2022-05-19 11:03 UTC, mijien0179 commented on pctory/Form1.cs
> +            grep.ShowDialog();
확인 해보니 해당 부분은 `멀티 이벤트 핸들러`로 처리하고 전달되는 `sender`로 값을 전달하는 게 중복 코드를 줄이는 데 도움이 될 것 같네요.

2022-05-22 13:51 UTC, gwanhwi approved these changes
확인 했읍니다 ^.^

2022-06-03 01:33 UTC, jihong99 approved these changes
그래프 기능 추가 확인했습니다

2022-06-03 08:58 UTC, cacaocoffee commented on pctory/Graph.cs
> +            chart4.Titles[0].Text = title + " 사용 시간";
String.mid함수는 c#에서 지원하지 않아 substring을 이용햇 구현해야합니다. 이런 작업 불필요한 작업을 줄이고 가시성을 늘리고자 저렇게 작성했습니다.

2022-06-03 09:11 UTC, mijien0179 commented on pctory/Graph.cs
> +            chart4.Titles[0].Text = title + " 사용 시간";
그럼 `substring`을 이용하면 되지 않을까요?

2022-06-03 10:11 UTC, mijien0179 approved these changes

2022-06-03 10:25 UTC, merged