UI
mijien0179/PCTORY pull request #5
Opened 2022-05-16 06:21 UTC by jihong99

.exe 파일 이용 시간 기록 및 UI menuStrip 기능 추가

2022-05-16 06:32 UTC, cacaocoffee commented
graph 39번째 줄 수정필요

2022-05-16 06:42 UTC, mijien0179 reviewed
커밋 확인 결과, Form의 dock=fill일 떄 form의 border가 가려지는 문제가 발생하여 해당 문제 수정했습니다.

2022-05-16 06:44 UTC, mijien0179 requested changes
form의 기본 크기를 수정하는 편이 좋을 것 같습니다

2022-05-16 06:50 UTC, mijien0179 requested changes
caption project는 굳이 필요하지 않은 것 같습니다. 해당 프로젝트는 git에서 제거해주세요.

2022-05-19 04:39 UTC, jihong99 commented on pctory/Form1.cs
> +            tracer = new Tracer(true).RunTrace();
프로그램 중지 및 강제종료 시 자동저장 기능을 추가하면 문제가 해결되어 추후에 추가하겠습니다.

2022-05-19 05:43 UTC, mijien0179 approved these changes
변경 내용 확인했습니다.

2022-05-19 07:00 UTC, cacaocoffee commented
변경 내용 확인했습니다.  merge 해도 될거 같아요

2022-05-19 07:07 UTC, cacaocoffee reviewed
merge해도 될거 같아요

2022-05-19 07:07 UTC, cacaocoffee commented on pctory/Form1.cs
> +                            Value = LastnameValue.GetCaptionData().Value.Item2
확인했어요 이부분이 string값만 뺴오는 거네요 저도 유용하게 사용할듯해요

2022-05-19 07:07 UTC, cacaocoffee approved these changes
merge해요

2022-05-19 07:08 UTC, merged